import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { similarityScore, distance, featureBreakdown, imageQuality } = req.body;

  const matchPercent = Math.round(similarityScore * 100);
  const verdict = matchPercent >= 80 ? 'STRONG MATCH' : matchPercent >= 60 ? 'POSSIBLE MATCH' : matchPercent >= 40 ? 'WEAK MATCH' : 'NO MATCH';

  const prompt = `You are an expert forensic facial recognition analyst with deep knowledge of biometric systems, NIST FRVT standards, and facial morphology. You are analyzing two face images that have been processed by a ResNet-34 deep learning model trained to 99.38% accuracy on the LFW benchmark.

Analysis Results:
- Overall Similarity Score: ${matchPercent}%
- Euclidean Distance (face descriptor): ${distance.toFixed(4)} (threshold: 0.6 for match)
- Verdict: ${verdict}
- Detection Confidence Image 1: ${(imageQuality.img1 * 100).toFixed(1)}%
- Detection Confidence Image 2: ${(imageQuality.img2 * 100).toFixed(1)}%

Feature Region Analysis (normalized similarity per region):
${Object.entries(featureBreakdown).map(([key, val]: [string, any]) => `- ${key}: ${(val * 100).toFixed(1)}%`).join('\n')}

Please provide a professional forensic analysis report (3-4 paragraphs) covering:
1. Overall match assessment and what the Euclidean distance means in practical terms
2. Which facial regions contributed most/least to the score and anatomical reasoning (e.g., interpupillary distance, nasal bridge geometry, mandibular structure, zygomatic arch proportions, philtrum width)
3. Confidence assessment considering image quality and any factors that may affect accuracy (pose, lighting, age differences, expression)
4. Final forensic opinion with appropriate caveats about this being an AI system

Write in authoritative but accessible language. Be specific about facial anatomy terms. Do not include headers or bullet points — write in flowing paragraphs.`;

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'anthropic-version': '2023-06-01',
        'x-api-key': process.env.ANTHROPIC_API_KEY || '',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 800,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      throw new Error('Claude API error');
    }

    const data = await response.json();
    const analysis = data.content[0]?.text || 'Analysis unavailable.';

    return res.status(200).json({ analysis });
  } catch (error) {
    console.error('Analysis error:', error);
    // Fallback analysis if Claude API isn't configured
    const fallback = generateFallbackAnalysis(matchPercent, distance, featureBreakdown, verdict);
    return res.status(200).json({ analysis: fallback });
  }
}

function generateFallbackAnalysis(matchPercent: number, distance: number, featureBreakdown: any, verdict: string): string {
  const topFeature = Object.entries(featureBreakdown).sort(([,a]: any, [,b]: any) => b - a)[0];
  const bottomFeature = Object.entries(featureBreakdown).sort(([,a]: any, [,b]: any) => a - b)[0];

  if (matchPercent >= 70) {
    return `The biometric analysis yields a similarity score of ${matchPercent}%, with a facial descriptor Euclidean distance of ${distance.toFixed(4)} — well within the 0.6 match threshold established by the ResNet-34 model's LFW benchmark calibration. This indicates a high probability that both images depict the same individual, consistent with a ${verdict} classification under standard NIST FRVT evaluation criteria.

The strongest contributing region was the ${topFeature[0].toLowerCase()} zone (${(Number(topFeature[1]) * 100).toFixed(1)}% similarity), reflecting consistent geometric proportions in that facial region across both images. The ${bottomFeature[0].toLowerCase()} area showed the most divergence (${(Number(bottomFeature[1]) * 100).toFixed(1)}%), which may be attributable to variations in expression, illumination angle, or slight head rotation between the two captures.

From a forensic standpoint, the deep neural embedding captures 128-dimensional feature vectors encoding interpupillary distance ratios, nasal bridge geometry, zygomatic arch width, and mandibular contour — all biometric invariants that persist across lighting changes and mild expression variations. The high overall correspondence across these structural landmarks supports a strong match determination.

Note: This analysis is generated by an AI system using face-api.js (99.38% LFW accuracy). Results should be treated as probabilistic estimates and not used as sole evidence for identity verification in high-stakes contexts.`;
  } else if (matchPercent >= 40) {
    return `The analysis yields a similarity score of ${matchPercent}% with an Euclidean distance of ${distance.toFixed(4)}, placing this comparison in an indeterminate zone near the 0.6 decision boundary. The ${verdict} classification suggests partial biometric overlap that warrants careful interpretation.

The ${topFeature[0].toLowerCase()} region demonstrates the highest correspondence (${(Number(topFeature[1]) * 100).toFixed(1)}%), suggesting possible shared structural features in that area. However, the ${bottomFeature[0].toLowerCase()} region shows significant divergence (${(Number(bottomFeature[1]) * 100).toFixed(1)}%), which may indicate different individuals or significant variation in capture conditions such as aging, lighting, or pose.

Several factors could be contributing to the ambiguous result: significant age gap between photos, heavy directional lighting altering shadow patterns on key landmarks, partial occlusion, or simply that these are two distinct individuals with some phenotypic similarities. The 128-dimensional feature vector captures fine-grained structural differences that the human eye may miss.

This result is inconclusive and should not be used for identity determination without additional corroborating evidence. Professional forensic examination with controlled reference images is recommended for any consequential identification.`;
  } else {
    return `The biometric comparison yields a low similarity score of ${matchPercent}% with an Euclidean distance of ${distance.toFixed(4)}, substantially exceeding the 0.6 match threshold. This is a strong ${verdict} indication, suggesting the two images most likely depict different individuals.

The feature vector analysis shows consistently low similarity across all facial regions, with the ${topFeature[0].toLowerCase()} zone showing the highest (but still low) correspondence at ${(Number(topFeature[1]) * 100).toFixed(1)}%. The ${bottomFeature[0].toLowerCase()} region is the most divergent at ${(Number(bottomFeature[1]) * 100).toFixed(1)}%. Such broad divergence across all anatomical zones — including structurally stable features like interpupillary distance and nasal bridge geometry — strongly indicates different subjects.

The ResNet-34 model encodes facial geometry in a rotation and illumination-robust manner, meaning that typical photographic variations would not produce this level of dissimilarity between images of the same person. The wide Euclidean distance in the high-dimensional embedding space reflects fundamental morphological differences between the two faces analyzed.

This analysis concludes with high confidence that these images do not depict the same individual. As with all AI-based systems, edge cases exist and the system achieves 99.38% accuracy on the LFW benchmark — meaning a small error rate remains.`;
  }
}
